name: Push code to APIdocs repo
# This Github action executes on push to `main`
# and Pushes the code folder `bci_essentials` to the
# ` APIdocs-for-bci-essentials-python` repo.

on:
  push:
    branches: ["main"]

jobs:
  push_code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout SOURCE repository
        uses: actions/checkout@v3

      - name: Push code to the `APIdocs` repository
        uses: nkoppel/push-files-to-another-repository@v1.1.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.APIDOCS_SYNC }}
        with:
          source-files: 'bci_essentials/ environment.yml pyproject.toml'
          destination-username: 'kirtonBCIlab'
          destination-repository: 'APIdocs-for-bci-essentials-python'
          destination-branch: 'main'
          destination-directory: './'
          commit-message: "Copy bci_essentials code directory on push to UPSTREAM/main"
          commit-email: 'n44412824+anup2ladder@users.noreply.github.com'